# Generated by Django 4.1.1 on 2022-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_bid_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid", name="bid", field=models.IntegerField(default=0),
        ),
    ]
