# Generated by Django 4.1.1 on 2022-09-16 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_bid_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid", name="bid", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserBid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
